source 'https://rubygems.org'

gem 'eventmachine', '~> 1.0.0'

gem 'vcap-concurrency', git: 'https://github.com/cloudfoundry/vcap-concurrency.git'
gem 'cf-message-bus', git: 'https://github.com/cloudfoundry/cf-message-bus.git'
gem 'vcap_common', git: 'https://github.com/cloudfoundry/vcap-common.git'
gem 'steno'

gem 'sinatra'
gem 'async_sinatra', github: "raggi/async_sinatra"

group :test do
  gem 'simplecov'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'rack-test'
  gem 'rspec-http', '~> 0.9'
end
